name: Continuous integration for Sirius.Vault.HSM

on:
  push:
    tags: "service-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up AdoptOpenJDK 1.11
        uses: joschi/setup-jdk@v1
        with:
          java-version: 11
          architecture: x64
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.6.1
          arguments: clean build printProperties
      - name: Check dir
        run: ls build/distributions
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Sirius.Vault.HSM-0.1.zip
          path: build/distributions
      - name: Publish to Registry
        uses: swisschain/Publish-Docker-Github-Action@master
        with:
          name: swisschains/sirius-vault-hsm
          dockerfile: docker/dockerfile.x64
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
          tag_names: true
          tag_name_skip: service-
      - name: copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          #           PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "scripts/build.sh,scripts/deploy.sh"
          target: "/root/"
      - name: build docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          #          port: ${{ secrets.PORT }}
          script: |
            export DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
            export DOCKER_PASSWORD="${{ secrets.DOCKER_PASSWORD }}"
            /root/scripts/build.sh
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          ##         PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: /root/scripts/deploy.sh
